package cream.model;
// Generated Jul 22, 2019 1:47:01 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import cream.util.DataTransferObject;

/**
 * Colors generated by hbm2java
 */
public class Colors implements java.io.Serializable, DataTransferObject {

	private long colorId;
	private String color;
	private Set<Product> products = new HashSet<Product>(0);

	public Colors() {
	}

	public Colors(long colorId, String color) {
		this.colorId = colorId;
		this.color = color;
	}

	public Colors(long colorId, String color, Set<Product> products) {
		this.colorId = colorId;
		this.color = color;
		this.products = products;
	}

	public long getColorId() {
		return this.colorId;
	}

	public void setColorId(long colorId) {
		this.colorId = colorId;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}


	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	public long getId() {
		// TODO Auto-generated method stub
		return 0;
	}

}
