package cream.model;
// Generated Jul 22, 2019 1:47:01 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import cream.util.DataTransferObject;

/**
 * OrderHistory generated by hbm2java
 */
public class OrderHistory implements java.io.Serializable, DataTransferObject {

	private long orderHistoryId;
	private long cartId;
	private Date date;
	private String streetAddress;
	private String city;
	private String state;
	private String zipcode;
	private List<Order> orderList;
	

	public OrderHistory(long orderHistoryId, long cartId, Date date, String streetAddress, String city, String state, String zipcode, List<Order> orderList) {
		this.orderHistoryId = orderHistoryId;
		this.cartId = cartId;
		this.date = date;
		this.streetAddress = streetAddress;
		this.city = city;
		this.state = state;
		this.zipcode = zipcode;
		this.orderList = orderList;
	}
	
	public long getCartId() {
		return cartId;
	}

	public void setCartId(long cartId) {
		this.cartId = cartId;
	}

	public List<Order> getOrderList() {
		return orderList;
	}

	public void setOrderList(List<Order> orderList) {
		this.orderList = orderList;
	}

	public String getStreetAddress() {
		return streetAddress;
	}

	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZipcode() {
		return zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public OrderHistory() {
	}

	
	public long getOrderHistoryId() {
		return this.orderHistoryId;
	}

	public void setOrderHistoryId(long orderHistoryId) {
		this.orderHistoryId = orderHistoryId;
	}
	
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Override
	public long getId() {
		// TODO Auto-generated method stub
		return 0;
	}

}
